---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"

dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    - JOBS=1

install:
  - yarn install

notifications:
  email: false

jobs:
  fail_fast: true

  include:
    - stage: deploy
      if: (branch = master OR tag IS present) AND type = push
      env: NAME=deploy
      script: node_modules/.bin/ember deploy production
